site_name: Attire
site_description: 'A short description of my project'
site_author: 'David Sosa Valdes'
site_url: 'https://github.com/CI-Attire'
# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/CI-Attire/Driver'
# Copyright
copyright: 'Copyright &copy; 2016 David Sosa Valdes'

theme: 'material'
extra:
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'images/ic_att.png'
  social:
    - type: 'github'
      link: 'https://github.com/davidsosavaldes'
    - type: 'twitter'
      link: 'https://twitter.com/itsdsv'
    - type: 'linkedin'
      link: 'https://mx.linkedin.com/in/david-sosa-valdes'

markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'
- Themes: 'themes.md'

extra_css:
  - 'stylesheets/extra.css'
